import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { format } from 'prettier';

const root = new URL('../', import.meta.url);
const source = await readFile(new URL('src/dashboard.js', root), 'utf8');
const helpers = source
  .replace(/^export (?=(?:async )?function )/gm, '')
  .replace(/^export default async function dashboard\(/m, 'async function dashboard(');

if (/^\s*(?:export|import)\b/m.test(helpers)) {
  throw new Error('Unsupported module syntax in Egern script source');
}

// Egern receives the documented anonymous default entry only.
// Named exports remain in src/dashboard.js for local tests and previews.
const entry = `// Generated by npm run build. Edit src/dashboard.js instead.
export default async function (ctx) {
  return dashboard(ctx);
}

`;
const output = await format(entry + helpers, {
  parser: 'babel',
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 90,
});
await mkdir(new URL('dist/', root), { recursive: true });
await writeFile(new URL('dist/dashboard.js', root), output);
console.log('Built dist/dashboard.js for Egern');
